# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f7b02e85d8267453a4c9ee695196305b643f871e20e27676a59cceab383393ad0beb1f1660a2082ddfa27b7588898ee7108709b9f20bc1e7e30a31eb4544d25

test:
  secret_key_base: 21d38d2bcd6dcd44ad910c8528920c9fd0d4ab3ad1995687831377b0ed1f86ec827dee2bf2823321b50a831754d77e2b9db16064641f970c2f55520cae1341c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
